# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3-8-g2c7106c
_src_path: git+https://git.sr.ht/~dmerej/copier-python
author_email: dimitri@dmerej.info
author_name: Dimitri Merejkowsky
package_import_name: tbump
project_description: Bump software releases
project_name: tbump
project_version: 6.9.0

